### ISSUE TITLE
No way to change global settings after init

### ISSUE THREAD

**Issue by errotan** [Pro-Club/MetroCL#12]
For example a full page reload is required to change language because the locale must be set before init, which is unacceptable if developing a single page application.

**Comment by olton** [comment]
I will add tracking of attribute data-locale for calendar and datepicker

**Comment by olton** [comment]
Thank you

**Comment by olton** [comment]
Added tracking for data-locale attribute for countdown, calendar, and datepicker

**Comment by olton** [comment]
Global vars used only for init default options for components
