### ISSUE TITLE
Init should be after DOM load

### ISSUE THREAD

**Issue by errotan** [Pro-Club/MetroCL#13]
Currently metro is inited immediatly without waiting for all DOM content to load. A mutation observer is attached immediatly which increases page load time, because on every new html node, js code has to run.

**Comment by olton** [comment]
Set <meta name="metro4:init" content="false">
And manually init after page is loaded: Metro.init()

**Comment by olton** [comment]
https://metroui.org.ua/v4/configuring.html#_metro_init
