### ISSUE TITLE
文档手册能否进行优化

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#17]
Hello: creator

I'm a fan of your styleframe.

It's just that your document style section is not detailed and optimized, such as validation, and you want to optimize your style in a tabular format.

**Comment by olton** [comment]
I don't quite understand what you mean

**Comment by chongzia** [comment]
Such as: Form validator
Navigation title ：Functions 
Contents of the pattern

It just tells us that it has this function. But it doesn't tell us how to use  pattern regular?

It is hoped that the manual document description will be more detailed and friendly and user-friendly.

And  hope that the reading habits of the document manual will be more unified.

Thanks for your reply. My English is poor.
