### ISSUE TITLE
two or more then window elements

### ISSUE THREAD

**Issue by penyin** [Pro-Club/MetroCL#21]
if i have two or more then window elements on the page
can this on the top when i touch someone window element? (z-index)

**Comment by olton** [comment]
Metro 4 is not currently implemented by the window manager, so for z-index you should monitor yourself

**Comment by penyin** [comment]
<img width="1920" alt="2018-01-31 4 58 54" src="https://user-images.githubusercontent.com/515626/35613873-3f50fa28-06a8-11e8-9c80-89bc206d1966.png">
<img width="1920" alt="2018-01-31 4 58 57" src="https://user-images.githubusercontent.com/515626/35613902-472410c8-06a8-11e8-8c45-c38e39ba1763.png">

**Comment by olton** [comment]
https://metroui.org.ua/v4/examples/desktop/desktop.html

**Comment by olton** [comment]
https://github.com/Pro-Club/MetroCL/tree/master/docs/examples/desktop

**Comment by penyin** [comment]
wow thanks, i try it.
