### ISSUE TITLE
Navigation View 

### ISSUE THREAD

**Issue by Chaoswriter96** [Pro-Club/MetroCL#22]
Hi Sergey

I have a shy question.
When I try to build a navview with the documenation I get a result which looks like that:
![navview](https://user-images.githubusercontent.com/22352687/35928663-f89a846a-0c2d-11e8-869a-82af901b1a13.JPG)

As you see is the icon in a wrong "column".

Code: 
(http://scratchpad.io/determined-stream-4140)

**Comment by olton** [comment]
Hi

https://codepen.io/olton/pen/YepZWB

**Comment by olton** [comment]
Maybe not latest version?

**Comment by Chaoswriter96** [comment]
I see now where the issue is...
It had problem with the PHP.

But its solved :)
