### ISSUE TITLE
Question about breakpoints

### ISSUE THREAD

**Issue by arjarn** [Pro-Club/MetroCL#28]
Very great job for this framework ! Become really awesome with last dev.

I've simple question, in breakpoint section, I can see for 1452px we must use **xxl** 

But with Navigation View (section Pane display modes) : min-with: 1452px is **zxl**

It's not very important but i'm wondering if it's error or not

**Comment by olton** [comment]
Hi
This is a type error. Right is xxl

**Comment by arjarn** [comment]
Thx for your replay, I close my "issue".
