### ISSUE TITLE
Can you add a new feature?

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#29]
In a mobile device, or in a PC device.
We often use the scroll bar drop-down and slide up and down with the screen touch.
Whether you can add a function to determine the bottom of the screen.
This allows us to know whether to initiate new requests to continue loading new content.
I think it's best to write a plugin instead of a wrapped function.
The plug-in should be easy to adjust.

So to Stepper also get better control.
that is can function as one timeline to use

**Comment by olton** [comment]
You can add an element to the bottom of the list and check when this element showing in a viewport with utils function `Metro.utils.inViewport(element)` and then add new content before this element.

**Comment by chongzia** [comment]
！！！~~~~~~~~~~~~
I didn't expect to use it this way when requesting data.
Thank you for the

timeline 😍

**Comment by arjarn** [comment]
Very nice tips !
