### ISSUE TITLE
Mistake in intro.html

### ISSUE THREAD

**Issue by Chaoswriter96** [Pro-Club/MetroCL#3]
Hi guys!

I found a mistake in the documentation. In the PRECODE its written: 

> <script **href**

instead of:

> <script **src**

Its in the chapters:
-> Quick Start
-> Starter Template
-> Short Demo

Related:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

![example](https://user-images.githubusercontent.com/22352687/31470041-849ae844-aee4-11e7-8985-b8dd1384a629.PNG)

**Comment by olton** [comment]
Thanks, fixed
