### ISSUE TITLE
donut BUG

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#30]
size | data-size | 100 | The width of component

at the when I resize the size time of
The component is not completely changed. exist mistake
The rest of the for the moment no fault found

**Comment by chongzia** [comment]
It is found that a second value must be set to solve the problem.

**Comment by chongzia** [comment]
Another mistake was found.
Font size cannot be adjusted.
I have a lot of fun with Donut.
haha~   awkward face

hope  have time to adjust
trouble you ~~ thank

**Comment by chongzia** [comment]
data-total
The number of decimal places is too long.
Exceeds the size of the component itself.
And it's not how much we want it to be.

**Comment by olton** [comment]
Where is the documentation written that the donut should change in size when changing the size of the parent or others?

**Comment by olton** [comment]
In the current version, donut will be only with fixed sizes

**Comment by chongzia** [comment]
Assuming that
data-total="35";
data-value="4"
See the results at this time.

**Comment by olton** [comment]
Thanks, fixed
https://codepen.io/olton/pen/JpOdgO

**Comment by chongzia** [comment]
I know that your current donut is calculated by percentage.
If I don't want to do a percentage calculation.
The finish is 18
So I'm starting with data-value and what's the reality 6 is 6 is not 33?

**Comment by chongzia** [comment]
data-total="18";
data-value="6"
displaying results 33%


I want to

data-total="18";
data-value="6"
displaying results 6

data-total="18";
data-value="15"
displaying results 18
Only donuts are involved in percentage calculations.
Do not allow the displayed value to participate in the percentage calculation.

through data-show-value=on/off

**Comment by olton** [comment]
Done
https://codepen.io/olton/pen/JpOdgO

**Comment by chongzia** [comment]
It's already working.
Thanks
Look forward to some statistics on his shape.
Like the vertical and the line  and the curve

**Comment by chongzia** [comment]
donut BUG
The calculated value.
It becomes a decimal.

**Comment by chongzia** [comment]
In the Google browser.

**Comment by olton** [comment]
Create live example please on codepen.io

**Comment by olton** [comment]
Read this before https://blog.codepen.io/documentation/

Please reopen this issue after creating working example on codepen.io
