### ISSUE TITLE
Sponsorship proposals

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#32]
hello
I'd love to be your sponsor.
But in China network 
Not very good access  facebook.
It's not easy for me.
And I also want to recommend your framework to some places in China.
And let more Chinese web developers see it.
If you can in China network
registered a  alipay account . 
And apply for a working server in aliyun to supply your project.
I think it should be well supported.
And I also want to know your alipay account.
Convenient to sponsor
I don't have any electronic currency.

https://global.alipay.com/
https://www.alibabacloud.com/

Also want to know your common network communication way.
In addition to the social software that you can't use in China.

**Comment by olton** [comment]
Hi! Thank you very much for your sponsorship proposal. I created an account on the patreon.com for sponsorship https://www.patreon.com/metroui

**Comment by olton** [comment]
Unfortunately, I do not have the financial ability to rent a server on alibabacloud :(

**Comment by chongzia** [comment]
https://www.patreon.com/metroui
I've tried it already.
When you link to the web page, I've tried it.
I can't register here, The registration button To me It's been disabled all the time.

**Comment by chongzia** [comment]
In addition, my server can temporarily share with you if you don't dislike.
Even though you don't mind.
cpu 2
memory 4
bandwidth 4MB
hard disk 80Gb 
Small server

**Comment by olton** [comment]
If you give me an FTP account data, I add your server to deploy script for deploying additional site mirror.

**Comment by chongzia** [comment]
How to give you？
my email  345414273@qq.com

**Comment by olton** [comment]
my email sergey@pimenov.com.ua

**Comment by chongzia** [comment]
Email has been sent.
title: 你好 很好笑认识你
