### ISSUE TITLE
The animation effect come to nothing to load 

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#33]
Metro.dialog.create(
{
	title: "Use Windows location service?",
	content: "<div>Bassus abactors ducunt ad triticum...</div>",
	actions:
	[
		{
			caption: "xx",
			cls: "js-dialog-close dark",
			onclick: function()
			{
				var url = "xxx/xxx/xxx";
				$.post(url,{id:id},function(data)
				{
					switch (data)
					{
						case 1:Metro.toast.create('xxx', null, 5000);return;//normal
						case 2:Metro.toast.create('xxx', null, 5000);return;//normal
						case 3:Metro.toast.create('xxx', null, 5000);return;//normal
						case 4:Metro.toast.create('<span class="mif-spinner5 ani-spin"></span> xxx', null, 2000);return;//report an error
						default: return false;
					}
				});
			}
		},
	]
});
This error cannot be solved by the code I wrote, it is a problem on the framework.

**Comment by olton** [comment]
Create pen on codepen.io with problem code.

**Comment by chongzia** [comment]
You don't use that server.

**Comment by olton** [comment]
I do not understand how to connect to it remotely to your server

**Comment by chongzia** [comment]
https://codepen.io/dreamcc/pen/XZzyxV
It's not very controlling.
The first time this site use.

**Comment by chongzia** [comment]
I don't know how to pass in a piece of json because I'm using PHP,

**Comment by olton** [comment]
This code is not working you use unknown tags: <foreach> for example

**Comment by chongzia** [comment]
Okay, so one of the errors is submitted.

**Comment by olton** [comment]
Please reopen this issue after creating working example on codepen.io

**Comment by chongzia** [comment]
https://codepen.io/dreamcc/pen/EQbGEM

**Comment by olton** [comment]
Thanks, fixed

**Comment by chongzia** [comment]
https://codepen.io/dreamcc/pen/EQbGEM 

Errors still exist
Unable to make ajax requests.
There is still no ajax request to be made.

**Comment by olton** [comment]
Use right url

**Comment by chongzia** [comment]
http://www.koobeen.com/a/a.html
Use this to view the error instance.
There is more  detailed error description in the page.

The doughnut bug can be seen directly from Google the browser

**Comment by olton** [comment]
![2018-02-17_18h54_17](https://user-images.githubusercontent.com/365108/36343366-01d4de5c-1414-11e8-8a1b-05652c4041f0.png)

**Comment by chongzia** [comment]
https://codepen.io/dreamcc/pen/EQbGEM
I have already rearrange
Json you can copy the following variable val 'json' to create a json file and put it in.
This mistake really bothers me.
must ask for a pop-up prompt.

**Comment by olton** [comment]
Use right url. See console output! You get 404 error for your url.

![2018-02-17_20h45_44](https://user-images.githubusercontent.com/365108/36344474-9199ac02-1423-11e8-97e3-1b43a87a3d5a.png)

**Comment by chongzia** [comment]
You must be able to see the error on the framework in the server environment.
Can you visit my website?
http://www.koobeen.com/a/a.html

**Comment by chongzia** [comment]
![1](https://user-images.githubusercontent.com/22745515/36344551-6469eb6e-1457-11e8-9666-8fe67ec20abe.png)

**Comment by olton** [comment]
get latest version

**Comment by chongzia** [comment]
Jq or  browser.?

**Comment by chongzia** [comment]
browser  Is the latest

**Comment by chongzia** [comment]
JQ  It's your recommendation 3.3

**Comment by olton** [comment]
https://codepen.io/olton/pen/eVyMLv

**Comment by chongzia** [comment]
![1](https://user-images.githubusercontent.com/22745515/36344828-ef652226-145a-11e8-9090-1f99c880700e.png)

**Comment by olton** [comment]
Ctrl+f5 clear browser cache

**Comment by chongzia** [comment]
Results the same

**Comment by olton** [comment]
I do not know how to help you, I have everything working

**Comment by chongzia** [comment]
It's the browser problem？ 
I use other browsers and this is really good.

Only on Google.

**Comment by olton** [comment]
Browser cache contains old version of the Metro 4

**Comment by chongzia** [comment]
I have tried other ways to solve the problem.
As long as you're testing it It's normal work
so it should be my own the problem
