### ISSUE TITLE
in the forms,about search

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#37]
data-on-search-button-click=""  function
Can you increase the incoming object and text content?

such easy to simplify code
such don't have to create a separate id.
don't have to look for objects in jq either.
Laziness is the beginning of sin. ~ (ノ◕ω◕)ノ

**Comment by olton** [comment]
I do not understand what you want

**Comment by chongzia** [comment]
In the form component.
about the component of the form search.
data-on-search-button-click =“...”
You define a custom search function for search.
In this function.
Can you add two default parameters in this function that we can customize?
When you add a click search button, the search content is passed in.
When we click search, the entire search input box object is passed in.

**Comment by olton** [comment]
arguments for callback `data-on-search-button-click`: input value, button
context: input element

**Comment by chongzia** [comment]
Can you give a detailed example of how this callback is used? About the parameters for the callback.
I can't understand use rules

**Comment by olton** [comment]
https://codepen.io/olton/pen/jZZOgq

**Comment by chongzia** [comment]
谢谢你~
