### ISSUE TITLE
Metro.utils.isObject(val);

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#39]
Other types of detection functions.
Temporary unused
This is used, and I think it should be a return to false or true value, rather than returning an object, and the function will report errors when it is not an object.
hope function that wants to detect types 
Everything ought to be such

The second parameter is open  ,return content.

var a = Metro.utils.isObject(data);
a  true or false

var b = Metro.utils.isObject(data,true);
b  content

**Comment by olton** [comment]
The behavior of the function will not change
