### ISSUE TITLE
Metro Icon request

### ISSUE THREAD

**Issue by Chaoswriter96** [Pro-Club/MetroCL#4]
Hi Sergey

Short question. Do you can add by the icons a "mif-dribbble-plus" and a "mif-dribbble-minus"?
When yes, do you can style the + and - like by "mif-user-plus/mif-user-minus".

Thx!

**Comment by olton** [comment]
how should these icons look like?

**Comment by olton** [comment]
Hi

how should these icons look like?

17 жовт. 2017 р. 7:14 пп "Chaoswriter96" <notifications@github.com> пише:

**Comment by Chaoswriter96** [comment]
The same style of the +/- symbols and putting them on the bottom corner of the dribbble icon.  The +/- symbols should also take 1/4 of the place of the dribbble icon (similar to the user icon).
Do you know more and less what I mean?

**Comment by olton** [comment]
To create MIF i'am use icomoon app. It no contains dribble+- icon. :(

**Comment by Chaoswriter96** [comment]
Is it then may possible to add these icons:
-> database-menu
-> database-add
-> database-remove

icon names are from the icomoon app

**Comment by olton** [comment]
@Chaoswriter96  The icons you specified are contained only in paid sets. I unfortunately can not afford to pay 69 dolars per set :(

**Comment by Chaoswriter96** [comment]
I will pay it. I will later write you an email what I need to send you the money :)

**Comment by olton** [comment]
I do not need money that I can not spend on myself :)

**Comment by olton** [comment]
You can use own self font with icons. Create it, link to your page and use. Metro 4 works with any font.

**Comment by Chaoswriter96** [comment]
When I understood it write we just pay 1x 59$.
So, for me its not a problem to give you the money so you can buy the Ultimate Pack for your projects :)
Cause we can also enlarge the icons for the framework :)

**Comment by olton** [comment]
@Chaoswriter96 If you want to help financially the project, here is my credit card number visa 4149517012608854. But I will not buy icons, I have more priority spending, such as medications for the heart after the operation.
