### ISSUE TITLE
Horizontal Menu not displaying correctly

### ISSUE THREAD

**Issue by xiecsuk** [Pro-Club/MetroCL#40]
I have a menu defined by the following code.

            <ul class="container-fluid h-menu fg-white bg-cobalt" style="font-weight:bold; font-size:24px text-align:center;">
                <li class="button place-left mif-apps fg-white bg-cobalt" data-role="popover"
                         data-popover-text="This is popover!"
                         data-popover-trigger="click"
                         data-popover-position="bottom">
                </li>
                <li class="app-bar-element place-right"><a href="#">Home</a></li>
                <li class="app-bar-element place-right"><a href="#">About Us</a></li>
                <li class="app-bar-element place-right"><a href="#">Admin</a></li>
            </ul>
The section in the manual concerning Menu | Horizontal Menu suggests that the menu items are centred within the container. Mine are placed at the top on the container and no amount of styling will alter the display of each element.

**Comment by olton** [comment]
Use right markup

**Comment by olton** [comment]
You are mix h-menu, appbar, container. Read the docs for h-menu

**Comment by xiecsuk** [comment]
The display of my menu bar is exactly as I want it as far as the positioning is concerned. The problem I have is that <style="font-weight:bold; font-size:24px text-align:center;"> is being ignored.
If I remove container-fluid, the menu bar does not reach the full width of the container. If I remove app-bar-element, the place-right instruction is ignored and all menu items appear on the left hand side of the menu bar; which I don't want.

**Comment by olton** [comment]
Can you draw what you want to get in the end?

**Comment by olton** [comment]
Maybe you should try flex tools ? https://metroui.org.ua/v4/flex.html

**Comment by xiecsuk** [comment]
This is the code I am using to create the header for my page:

> <body class="container" style="background-color:#FFFFBF; max-width:1080px;">
    <header class="header row">
        <img src="~/images/Header.jpg" alt="HeaderLogo">
        <div class="app-bar-element" style="background-color:#FFFFBF; font-weight:bold; font-size:18px; position:absolute; right:20px; top:20px;">
            <a href="#">Sign-in</a>
        </div>
        <ul class="container-fluid h-menu fg-white bg-cobalt" style="font-weight:bold; font-size:24px; text-align:center">
            <li class="button place-left mif-apps" data-role="popover"
                data-popover-text="This is a popover!"
                data-popover-trigger="click"
                data-popover-position="bottom">
            </li>
            <li class="app-bar-element place-right"><a href="#")">Home</a></li>
            <li class="app-bar-element place-right"><a href="#")">About Us</a></li>
            <li class="app-bar-element place-right"><a href="#")">Contact Us</a></li>
            <li class="app-bar-element place-right"><a href="#")">Weather</a></li>
            <li class="app-bar-element place-right"><a href="#">Location</a></li>
            <li class="app-bar-element place-right"><a href="#">Admin</a></li>
        </ul>
    </header>
	.
	.
</body>

The section containing the image is about 5 cm deep with the Sign-in button at the top right. The 
ul.../ul   section is the toolbar which should extend the full width of the container; one element at the left hand end which displays a popover when selected - the other 6 elements of the toolbar are displayed at the right hand end, and should be centred on the toolbar, in bold type, and 24 px tall; but they're not. The style declaration seems to be completely ignored. As I said previously, the layout is exactly as I want it. It is just the styling of the 6 toolbar elements that is missing.

**Comment by olton** [comment]
I can help you then and only when you start using the elements of Metro 4 as they are described in the documentation. You wrote a mixture of different components and want it to work. It does not happen!

**Comment by olton** [comment]
![1](https://user-images.githubusercontent.com/365108/36394194-c7e41862-15bb-11e8-86c2-2b364b518ab1.jpg)

**Comment by xiecsuk** [comment]
I disagree with your remarks! The <ul></ul> section is almost identical to the code in the Horizontal Menu section of Menu. I have specified container-fluid to give me a full width container. I have had to include app-bar-element otherwise the place-right instruction is ignored. The only thing that has been ignored is my Style section, otherwise the result would have been perfect.

**Comment by olton** [comment]
Firstly - the menu initially takes up all the width and you do not need to add separate classes for this.
Secondly, an element with the class .app-bar-element in Metro 4 is not present.
Thirdly, if you need to center the menu items, you do not need to invent anything. It is necessary to read carefully the documentation and use the existing utilitarian flex classes.

https://codepen.io/olton/pen/ZrxXvq

**Comment by xiecsuk** [comment]
It would appear that we are never going to agree on what is happening versus what you tell me should happen. It is not worth me spending any more time on this so I will say goodbye.
