### ISSUE TITLE
Will consider using Microsoft's new design language fluent design system?

### ISSUE THREAD

**Issue by AGDholo** [Pro-Club/MetroCL#42]
Please use Edge browser or IE browser to open [https://fluent.microsoft.com/](https://fluent.microsoft.com/)

**Comment by olton** [comment]
Firstly, Metro 4 does not implement Fluent design, but it is an improvement from the author's point of view, the Metro UI CSS library, which is also a subjective view of the author on the library of Metro-style components.

Secondly: Microsoft itself does not yet understand how everything should work in a fluent design. there is a concept, there is no realization.
