### ISSUE TITLE
Request form validators, use regular usage, and make some instructions in the manual.

### ISSUE THREAD

**Issue by chongzia** [Pro-Club/MetroCL#43]
in the form validation about Regular expression  how to use.
If it's the same as your third generation.
There is a detailed use case description.
I would be very grateful.because I didn't get him out.

Furthermore, there are bugs in the form validation component.
When I click on the button time
The correct way to do this is to determine whether the button needs to be validated.
is Instead of the irrelevant button, it will also participate in the validation program.

about validation function in the digital judgment 
Digital validation is problematic.Here,The said Is not number function
In my opinion, you should build more Verify the instance composite application tests to meet the use of functions  tests

**Comment by olton** [comment]
Docs update. Create pen on codepen.io with problem code.

**Comment by chongzia** [comment]
It feels like it's been solved.
