### ISSUE TITLE
Window Feature Glitch (Chrome) 

### ISSUE THREAD

**Issue by Chaoswriter96** [Pro-Club/MetroCL#7]
Hi mates!

I found a glitch by the window feature. 
On the left side you see Google Chrome (62.0.3202.94) and on the right side Firefox. 
The glitch just exists in Google Chrome so far.

Described:
Google Chrome enlarge the window automaticly on the bottom side.

![glitch](https://user-images.githubusercontent.com/22352687/32981666-d42fb234-cc78-11e7-92f1-56af143a618b.PNG)

**Comment by olton** [comment]
Hi. Only in the picture I can not determine the problem, I need a link to the example

**Comment by Chaoswriter96** [comment]
My test site:
[https://github.com/Chaoswriter96/FCW](url)

Example site is "trainer-add.php"

**Comment by olton** [comment]
Please get the latest version of Metro 4

**Comment by olton** [comment]
1) put head open tag before meta (meta tag is a part of the head)
2) if you include metro-all.css, don't include other css files (metro-all contains all styles)

**Comment by olton** [comment]
https://codepen.io/olton/pen/vWpgbO all ok in Chrome
![2017-11-18_18h05_03](https://user-images.githubusercontent.com/365108/32982316-1fdd3636-cc8b-11e7-8554-81082bcb4e90.png)
